trk-fb-world.Debug/Controllers/DefaultController.cs
using Facebook;
using Microsoft.AspNet.Mvc.Facebook;
using MvcHelper.Facebook.Models;
using Newtonsoft.Json.Linq;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading;
using System.Web;
using System.Web.Mvc;
using System.Web.Script.Serialization;
using TurkcellFacebookDunyasi.App.App_Manager;
using TurkcellFacebookDunyasi.App.Filters;

namespace TurkcellFacebookDunyasi.App.Controllers
{
    
    public class DefaultController : BaseController
    {
        public ActionResult Default()
        {
            return RedirectToAction("Default", "Start");
        }
    }
}

trk-fb-world.Debug/Controllers/TiklaAraController.cs
using Kendo.Mvc.UI;
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TurkcellFacebookDunyasi.App.App_Manager;
using TurkcellFacebookDunyasi.App.Filters;
using TurkcellFacebookDunyasi.App.Models;
using TurkcellFacebookDunyasi.Core;
using TurkcellFacebookDunyasi.Core.Interfaces;
using TurkcellFacebookDunyasi.Core.Services;

namespace TurkcellFacebookDunyasi.App.Controllers
{
    [FbAuthorize]
    [SSOAuthorize]
    [ActionLog]
    public class TiklaAraController : BaseController
    {
        private readonly ClickToCallPreferenceService servicePreference;
        private readonly IClickToCallRepository repClickToCall;
        private readonly ClickToCallUserBlockService servClickToCallUserBlock;
        private readonly ClickToCallFreeService servClickToCallFree;

        public TiklaAraController(ClickToCallPreferenceService servicePreference, IClickToCallRepository repClickToCall, ClickToCallUserBlockService servClickToCallUserBlock, ClickToCallFreeService srvClickToCallFree)
        {
            this.servicePreference = servicePreference;
            this.repClickToCall = repClickToCall;
            this.servClickToCallUserBlock = servClickToCallUserBlock;
            this.servClickToCallFree = srvClickToCallFree;
        }

        public PartialViewResult Default()
        {
            TiklaAraModel model = new TiklaAraModel(); 
            return PartialView(model);
        }

        public PartialViewResult Call(int Id)
        {
            CallModel model = new CallModel();

            model.IsAvailable = servicePreference.IsAvailable(Id);
            model.FriendData = UserFb.Friends.Where(p => p.UserId == Id).SingleOrDefault();

            ServiceManager.ServiceHandlers.TiklaAraHandler srvTiklaAra = new ServiceManager.ServiceHandlers.TiklaAraHandler();
            model.RemainingBalance = srvTiklaAra.GetRemainingBalance(UserFb.Data.Msisdn);

            return PartialView(model);
        }

        [HttpPost]
        public JsonResult CallStart(int FriendUserId)
        {
            bool IsBirthdayCall = UserFb.TodayBornFriends.Any(f => f.UserId == FriendUserId);
            bool HadFreeCall = servClickToCallFree.HadFreeCallWith(UserFb.Data.Id, FriendUserId);
            bool IsFreeCall = (IsBirthdayCall && HadFreeCall != true);

            //Yukaridaki iki alan, yapilan aramanin bir dogum günü aramasi olup olmadigini ve 
            //dogum gunu ise bile, bu kullanici ile son 1 yil icerisinde ücretsiz arama yapilip
            //yapilmadigini tutuyor. Sonrasi, TiklaAraHandler.StartCall cagrisina uygun sekilde
            //isFree = true ya da false gecirmeye kaliyor.

            try
            {
                string ParticipantAMsisdn = UserFb.Data.Msisdn;
                string ParticipantBMsisdn = UserFb.Friends.Where(p => p.UserId == FriendUserId).SingleOrDefault().Msisdn;

                ServiceManager.ServiceHandlers.TiklaAraHandler srvTiklaAra = new ServiceManager.ServiceHandlers.TiklaAraHandler();
                long CallId = srvTiklaAra.StartCall(ParticipantAMsisdn, ParticipantBMsisdn, IsFreeCall);

                //ClickToCallRepository'ye kayit dustukten sonra, eger gorusme ücretsiz yapildi ise
                //ClickToCallFreeRepository'ye de ayni kayit dusulmeli.
                if (IsFreeCall)
                {
                    var entClickToCallFree = new Core.ClickToCallFree
                    {
                        CallId = CallId,
                        ParticipantAUserId = UserFb.Data.Id,
                        ParticipantBUserId = FriendUserId,
                    };
                    servClickToCallFree.SaveAndCommit(entClickToCallFree);
                }

                var entClickToCall = new Core.ClickToCall();
                entClickToCall.CallId = CallId;
                entClickToCall.ParticipantAMsisdn = ParticipantAMsisdn;
                entClickToCall.ParticipantAUserId = UserFb.Data.Id;
                entClickToCall.ParticipantBMsisdn = ParticipantBMsisdn;
                entClickToCall.ParticipantBUserId = FriendUserId;

                repClickToCall.SaveAndCommit(entClickToCall);

                return Json(new { result = 1 });
            }
            catch (Exception)
            {
                return Json(new { result = 0 });
            }
        }

        public PartialViewResult HowItWorks() {
            return PartialView();
        }

        public PartialViewResult Preferences()
        {
            TiklaAraTercihlerModel model = new TiklaAraTercihlerModel();

            ServiceManager.ServiceHandlers.TiklaAraHandler srvTiklaAra = new ServiceManager.ServiceHandlers.TiklaAraHandler();
            model.RemainingBalance = srvTiklaAra.GetRemainingBalance(UserFb.Data.Msisdn);

            return PartialView(model);
        }


        public PartialViewResult PreferencesForm()
        {
            return PartialView(servicePreference.GetByUserId(UserFb.Data.Id));
        }

        [HttpPost]
        public PartialViewResult PreferencesForm(ClickToCallPreference entity)
        {
            servicePreference.Save(entity);

            return PartialView("Result",
                new ResultModel
                {
                    Type = ResultModel.ResultType.success
                });
        }


        public PartialViewResult UserBlocks()
        {            
            return PartialView();
        }

        [HttpPost]
        public JsonResult UserBlocks(string FriendIds)
        {           
            servClickToCallUserBlock.Add(UserFb.Data.Id, FriendIds.Split(',').ToArray());            
            return Json(new { result = "1" }, "text/plain");
        }

        [HttpPost]
        public JsonResult RemoveBlock(string FbId)
        {
            servClickToCallUserBlock.DeleteByFbId(UserFb.Data.Id, FbId);
            return Json(new { result = "1" }, "text/plain");
        }



        public PartialViewResult UserBlockList()
        {
            ClickToCallUserBlockListModel model = new ClickToCallUserBlockListModel();

            model.BlockListData = servClickToCallUserBlock.GetByUserId(UserFb.Data.Id);

            return PartialView(model);
        }


        public PartialViewResult Promote() {
            return PartialView();
        }

        public JsonResult PrmoteFriends()
        {
            bool HasClickToCallRecords = false;

            var PromotedClickToCalls = new List<Core.ClickToCallPromoteModel>();
            var ClickToCallPrmoteFriends = new List<ClickToCallFriendModel>();

            //SON ARAMA KAYITLARI
            var LastCalls = repClickToCall.LastCalls(UserFb.Data.Id).Take(6).ToList();

            if (LastCalls.Count() > 0)
            {
                HasClickToCallRecords = true;
                PromotedClickToCalls.AddRange(LastCalls);

                //SIK KONUŞTUKLARIN
                var frequentlyCalled = repClickToCall.FrequentlyCalled(UserFb.Data.Id).Take(6).ToList();
                PromotedClickToCalls.AddRange(frequentlyCalled);

                ClickToCallPrmoteFriends = PromotedClickToCalls.Join(UserFb.Friends,
                                                            p => p.FriendUserId,
                                                            l => l.UserId,
                                                            (l, p) => new ClickToCallFriendModel
                                                            {
                                                                UserId = l.FriendUserId,
                                                                FbId = p.FbId,
                                                                FirstNameView = p.FirstNameView,
                                                                LastNameView = p.LastNameView,
                                                                PictureLink = p.PictureLink,
                                                                IsClickToCallBlock = p.IsClickToCallBlock,
                                                                IsClickToCallInvisible = p.IsClickToCallInvisible,
                                                                PromoteType = l.PromoteType,
                                                            }).ToList();
            }
            
            //ARKADAŞ LİSTENDEN RANDOM 6 KİŞİYİ ClickToCallFriendModel e aktar
            var randomFriends = UserFb.Friends.Join(UserFb.Friends.Where(p => p.IsClickToCallInvisible == false && p.IsClickToCallBlock == false),
                                                        p => p.UserId,
                                                        l => l.UserId,
                                                        (l, p) => new ClickToCallFriendModel
                                                        {
                                                            UserId = l.UserId,
                                                            FbId = p.FbId,
                                                            FirstNameView = p.FirstNameView,
                                                            LastNameView = p.LastNameView,
                                                            PictureLink = p.PictureLink,
                                                            IsClickToCallBlock = p.IsClickToCallBlock,
                                                            IsClickToCallInvisible = p.IsClickToCallInvisible,
                                                            PromoteType = Core.ClickToCallPromoteModel.PromoteTypes.RandomFriends,
                                                        })

trk-fb-world.Debug/Views/TiklaAra/Call.cshtml
@using TurkcellFacebookDunyasi.Com.Helpers

@model TurkcellFacebookDunyasi.App.Models.CallModel

<script>
    $(document).ready(function () {
        //$("select").kendoDropDownList();
        $("#btnAra").click(function () {

            $("#CallStep1").hide();
            $("#CallStep2").fadeIn('slow');

            var postData = { FriendUserId: @Model.FriendData.UserId };

            $.ajax({
                url: '/TiklaAra/CallStart/',
                type: "POST",
                data: postData,
                dataType: 'json',
                success: function (response) {

                    if (response.result == 0) {
                        $("#CallStep2").hide();
                        $('#CallStepError').show();
                    }

                }
            });

        });
    });
</script>

<div id='colorboxContentainer2'>
    <div id="colorboxContent2">
		<h2 class="colorboxHeader">Arkadaşını Tıkla Ara</h2>              

        <section id="CallStep1">
          
            <section id="remainingBalance"></section>
            <script>
                partialViewLoad("remainingBalance", "/TiklaAra/RemainingBalance");
            </script>

        <section class="fLeft profil">
            <figure class="fLeft user userLarge">
                <img src="@Model.FriendData.PictureLink" border="0" />
            </figure>
            <section class="fRight fBoldIta">
                <p class="large">@Model.FriendData.FirstNameView @Model.FriendData.LastNameView</p>
                <ins></ins>

                @if (Model.IsAvailable) {
                    <a href="javascript:;" id="btnAra" data-ga="Araniyor" class="dtCall">Tıkla ARA</a>
                }
                else
                {
                    <section class="error">Arkadaşın bu zaman diliminde aranmak istemiyor.</section>
                }

            </section>
        </section>

          <section class="textAreaBottom fIta">Lorem Ipsum has been the industry's standard dummy text ever since the 1500s , when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries..</section>
            
        </section>

        <section id="CallStep2" style="display:none;">
            <ins class="space35"></ins>
            
            <section class="calling">

                <section class="contacts fLeft">
                    <img src="@Model.UserFb.Data.FbProfilePicture" class="contact1" />
                    <img src="@Model.FriendData.PictureLink" class="contact2" />
                </section>

                <section class="callingSuccess fRight fIta">
                    <b>Aranıyor<img src="@PathHelper.UrlStatic/images/global/callingPoint.gif" /></b><br />
                    Karşı taraf aramayı kabul ettiğinde, Turkcell sizi arayacak ve aradığınız kişiye bağlayacak.
                </section>
                
            </section>

        </section>

        <section id="CallStepError" class="error" style="display:none;">
            <ins class="space35"></ins>

            ARAMA ŞU AN İÇİN GERÇEKLEŞTİRİLEMİYOR! <br /> 
            Lütfen daha sonra tekrar deneyiniz...

        </section>

    </div>
</div>

trk-fb-world.Debug/Views/TiklaAra/Default.cshtml
@using TurkcellFacebookDunyasi.Com.Helpers
@using TurkcellFacebookDunyasi.App.Models

<script>
    tooltipsy();

    var dsFriendsClickToCall;

    $(function () {

        var _kTmpFriend = kendo.template($("#tmpFriendsClickToCall").html());

        dsFriendsClickToCall = new kendo.data.DataSource({
            transport: {
                read: {
                    url: "/User/GetAllFriends",
                    dataType: "json"
                }
            },

            schema: {
                model: {
                    fields: {
                        UserId: {},
                        FbId: {},
                        FirstNameView: { type: "string" },
                        LastNameView: { type: "string" }
                    }
                }
            },

            change: function () {
                $("#friendsClickToCall").html(kendo.render(_kTmpFriend, this.view()));
                $(".nano").nanoScroller({ alwaysVisible: true });
                $(".ajax").colorbox();
                //$("#friendsClickToCall").hide().slideDown('fast', 'easeOutQuad');
            }
        });


        //FILTERS
        $('#rdClickToCallFriendGroup input').click(function () { ClickToCallFriendsFilter($(this).attr("data-action")); });

        $("#txtFriendSearch").on("keyup", function (e) {
            kGridSearch(dsFriendsClickToCall, e);

            if ($('#rdAll').attr("checked") != "checked") {
                $('#rdAll').click(); $('#rdAll').click();
            }

        });
        // ------------ //

        $('#rdAll').click();

    });


    function ClickToCallFriendsFilter(FilterType) {

        if (FilterType == 'All') {
            dsFriendsClickToCall.filter({});
            dsFriendsClickToCall.sort({});
        }
        else {
            var filters = { logic: 'and', filters: [{ field: FilterType, operator: "gt", value: 0 }] };

            var sort = { field: FilterType, dir: "desc" };

            dsFriendsClickToCall.filter(filters);
            dsFriendsClickToCall.sort(sort);
        }
    }

</script>

<section class="subContainer">

    <section class="tabContents">
        <section class="tabContent">
            
            <h2>ARKADAŞLARINI TIKLA ARA</h2>

            <section class="fRight" style="margin-top:-50px">
                <a href="/TiklaAra/HowItWorks" class="ajax pinkButton" data-ga="TiklaAraNasilCalisir"> <img src="@PathHelper.UrlStatic/images/icons/help.png" /> NASIL ÇALIŞIR</a>
                <a href="/TiklaAra/Preferences" class="ajax blueButton ttB" title="Tercihler" data-ga="TiklaAraTercihler"> <img src="@PathHelper.UrlStatic/images/icons/setting.png" /></a>
            </section>

            <ins class="space35"></ins>

            <section class="invoiceDetailHeader fLeft">

                <section class="invoiceAmount callRadio">
                    <section class="rdGroup" id="rdClickToCallFriendGroup">
                        <input type="radio" name="rb" value="3" id="rdAll" data-action="All" class="radioFilter" checked="checked" /> <label for="rdAll">Tümü</label>
                        <input type="radio" name="rb" value="2" id="rdOutGoing" data-action="OutGoingCallCount" class="radioFilter" /> <label for="rdOutGoing">Sık Aradıklarım</label>
                        <input type="radio" name="rb" value="3" id="rdIncoming" data-action="InComingCallCount" class="radioFilter" /> <label for="rdIncoming">Sık Arayanlar</label>
                    </section>
                </section>

                <section class="invoiceFilter specialText top">
                    <input id="txtFriendSearch" type="text" placeholder="Arkadaşlarını Ara..." style="width:230px" />
                    <span class="searchBtn"></span>
                </section>

            </section>

            <ins></ins>

            
            <section class="friendBox2">
                <section class="_top"></section>
                <section class="_cont">

                    <script id="tmpFriendsClickToCall" type="text/x-kendo-template">

                        @Html.Partial("FriendKTemplate")

                    </script>
                    
                    <section class="friendContainer nano" style="display:block; height: 500px;">
                        <section class="content" id="friendsClickToCall">
      
                            Arkadaş listeniz yükleniyor...

                        </section>
                    </section>
                    


                    </section>
                <section class="_bot"></section>
            </section>
        </section>
    </section>

</section>

trk-fb-world.Debug/Views/TiklaAra/HowItWorks.cshtml
@using TurkcellFacebookDunyasi.Com.Helpers

<div id='colorboxContentainer4'>
    <div id="colorboxContent4">
		<h2 class="colorboxHeader">Nasıl Çalışır?</h2>

        <section>
            <img src="@PathHelper.UrlStatic/images/global/tiklaAraHowItWorks.png" />
            <section class="textContent fIta">
                Arama isteğinde bulunduğunuzda, ilk olarak telefonunuz 757 52 70 numarasından çalar. <br />
                Gelen aramayı cevapladığınızda, görüşme yapmak istediğiniz kişinin telefonu çalar. <br />
                Arama yapmak istediğiniz kişi telefonunu açtığında, görüşmeniz başlar. İlk 10 dakikalık görüşme bedava, daha sonraki iki arama 40 ar kuruş ve 10 ar dakika ile sınırlı.<br />
                Ücretsiz arama haklarınız bittikten sonra, dakika başına 40 kuruş olarak ücretlendirilirsiniz. Sadece Facebook arkadaşlarınız ile görüşebilirsiniz.
            </section>
        </section>

    </div>
</div>

trk-fb-world.Debug/Views/TiklaAra/Preferences.cshtml
@model TurkcellFacebookDunyasi.App.Models.TiklaAraTercihlerModel
@using TurkcellFacebookDunyasi.Com.Helpers

<script>
    
    $(".ajax").colorbox();
    function preferenceFormOnSuccess() {
        $('#preferenceOptions').hide();
        $('#preferenceResult').css("display", "block");
    }
</script>


<div id='colorboxContentainer3'>
    <div id="colorboxContent3">
        
		<h2 class="colorboxHeader">Aranma Tercihleri</h2>

        <section id="preferenceOptions">

        
            <section id="remainingBalance"></section>
            <script>
                partialViewLoad("remainingBalance", "/TiklaAra/RemainingBalance");
            </script>            

            <ins></ins>    

            @Html.Action("PreferencesForm", "TiklaAra")

            <ins class="space35"></ins>

        </section>

        <section id="preferenceResult" style="display:none;">
            <ins class="space35"></ins>
            <section class="success">
                <br /> Tercihleriniz başarılı bir şekilde kaydedilmiştir.. <br /> <ins class="space35"></ins>
            </section>
            <ins></ins>
        </section>

        <ins class="space35"></ins>
    </div>
</div>

trk-fb-world.Debug/Views/TiklaAra/PreferencesForm.cshtml
@model TurkcellFacebookDunyasi.Core.ClickToCallPreference

@{
            
    string AvailableWeekDayTimeBegin;
    string AvailableWeekDayTimeEnd;
    string AvailableWeekEndTimeBegin;
    string AvailableWeekEndTimeEnd;
                        
    if (Model == null) {                                
        AvailableWeekDayTimeBegin = ConfigManager.GetInstance().AvailableWeekDayTimeBegin;
        AvailableWeekDayTimeEnd = ConfigManager.GetInstance().AvailableWeekDayTimeEnd;
        AvailableWeekEndTimeBegin = ConfigManager.GetInstance().AvailableWeekEndTimeBegin;
        AvailableWeekEndTimeEnd = ConfigManager.GetInstance().AvailableWeekEndTimeEnd;
    }
    else
    {
        AvailableWeekDayTimeBegin = Model.AvailableWeekDayTimeBegin;
        AvailableWeekDayTimeEnd = Model.AvailableWeekDayTimeEnd;
        AvailableWeekEndTimeBegin = Model.AvailableWeekEndTimeBegin;
        AvailableWeekEndTimeEnd = Model.AvailableWeekEndTimeEnd;
    }
}


<script>

    $(function () {

        $('#AvailableWeekDayTimeBegin').val('@AvailableWeekDayTimeBegin');
        $('#AvailableWeekDayTimeEnd').val('@AvailableWeekDayTimeEnd');
        $('#AvailableWeekEndTimeBegin').val('@AvailableWeekEndTimeBegin');
        $('#AvailableWeekEndTimeEnd').val('@AvailableWeekEndTimeEnd');

    });

</script>


@using (Ajax.BeginForm(null, null, new AjaxOptions { UpdateTargetId = "PageForm", LoadingElementId = "LoadingForm", OnSuccess = "preferenceFormOnSuccess" }, new { @id = "PageForm" }))
{        
    
        @Html.HiddenFor(a => a.Id)
        @Html.HiddenFor(a => a.UserId)
        @Html.HiddenFor(a => a.CreateDate)        
    
        <h3 class="colorboxSubHead">Gizlilik Modu</h3>

        <section class="rdGroup">           
            @Html.RadioButtonFor(r => r.IsInvisible, true, new { id="rdInvisibleTrue", @class = "radioFilter"}) <label for="rdInvisibleTrue">Aramaya Kapalı</label>
            @Html.RadioButtonFor(r => r.IsInvisible, false, new { id="rdInvisibleFalse", @class = "radioFilter"}) <label for="rdInvisibleFalse">Aranabilir</label>
        </section>

        <ins></ins>

        <h3 class="colorboxSubHead">Aranma Saatleri</h3>

        <section class="hours">
            <section class="hourTitle">HAFTA İÇİ </section>
            <section class="hourInput">

                <select name="AvailableWeekDayTimeBegin" id="AvailableWeekDayTimeBegin" style="width:130px">
                    <option value="00:00">00:00</option>
                    <option value="01:00">01:00</option>
                    <option value="02:00">02:00</option>
                    <option value="03:00">03:00</option>
                    <option value="04:00">04:00</option>
                    <option value="05:00">05:00</option>
                    <option value="06:00">06:00</option>
                    <option value="07:00">07:00</option>
                    <option value="08:00">08:00</option>
                    <option value="09:00">09:00</option>
                    <option value="10:00">10:00</option>
                    <option value="11:00">11:00</option>
                    <option value="12:00">12:00</option>
                    <option value="13:00">13:00</option>
                    <option value="14:00">14:00</option>
                    <option value="15:00">15:00</option>
                    <option value="16:00">16:00</option>
                    <option value="17:00">17:00</option>
                    <option value="18:00">18:00</option>
                    <option value="19:00">19:00</option>
                    <option value="20:00">20:00</option>
                    <option value="21:00">21:00</option>
                    <option value="22:00">22:00</option>
                    <option value="23:00">23:00</option>
                </select>

                <select name="AvailableWeekDayTimeEnd" id="AvailableWeekDayTimeEnd" style="width:130px">
                    <option value="00:00">00:00</option>
                    <option value="01:00">01:00</option>
                    <option value="02:00">02:00</option>
                    <option value="03:00">03:00</option>
                    <option value="04:00">04:00</option>
                    <option value="05:00">05:00</option>
                    <option value="06:00">06:00</option>
                    <option value="07:00">07:00</option>
                    <option value="08:00">08:00</option>
                    <option value="09:00">09:00</option>
                    <option value="10:00">10:00</option>
                    <option value="11:00">11:00</option>
                    <option value="12:00">12:00</option>
                    <option value="13:00">13:00</option>
                    <option value="14:00">14:00</option>
                    <option value="15:00">15:00</option>
                    <option value="16:00">16:00</option>
                    <option value="17:00">17:00</option>
                    <option value="18:00">18:00</option>
                    <option value="19:00">19:00</option>
                    <option value="20:00">20:00</option>
                    <option value="21:00">21:00</option>
                    <option value="22:00">22:00</option>
                    <option value="23:00">23:00</option>
                </select>

            </section>
        </section>
        <section class="hours">
            <section class="hourTitle">HAFTA SONU </section>
            <section class="hourInput">

                <select name="AvailableWeekEndTimeBegin" id="AvailableWeekEndTimeBegin" style="width:130px">
                    <option value="00:00">00:00</option>
                    <option value="01:00">01:00</option>
                    <option value="02:00">02:00</option>
                    <option value="03:00">03:00</option>
                    <option value="04:00">04:00</option>
                    <option value="05:00">05:00</option>
                    <option value="06:00">06:00</option>
                    <option value="07:00">07:00</option>
                    <option value="08:00">08:00</option>
                    <option value="09:00">09:00</option>
                    <option value="10:00">10:00</option>
                    <option value="11:00">11:00</option>
                    <option value="12:00">12:00</option>
                    <option value="13:00">13:00</option>
                    <option value="14:00">14:00</option>
                    <option value="15:00">15:00</option>
                    <option value="16:00">16:00</option>
                    <option value="17:00">17:00</option>
                    <option value="18:00">18:00</option>
                    <option value="19:00">19:00</option>
                    <option value="20:00">20:00</option>
                    <option value="21:00">21:00</option>
                    <option value="22:00">22:00</option>
                    <option value="23:00">23:00</option>
                </select>

                <select name="AvailableWeekEndTimeEnd" id="AvailableWeekEndTimeEnd" style="width:130px">
                    <option value="00:00">00:00</option>
                    <option value="01:00">01:00</option>
                    <option value="02:00">02:00</option>
                    <option value="03:00">03:00</option>
                    <option value="04:00">04:00</option>
                    <option value="05:00">05:00</option>
                    <option value="06:00">06:00</option>
                    <option value="07:00">07:00</option>
                    <option value="08:00">08:00</option>
                    <option value="09:00">09:00</option>
                    <option value="10:00">10:00</option>
                    <option value="11:00">11:00</option>
                    <option value="12:00">12:00</option>
                    <option value="13:00">13:00</option>
                    <option value="14:00">14:00</option>
                    <option value="15:00">15:00</option>
                    <option value="16:00">16:00</option>
                    <option value="17:00">17:00</option>
                    <option value="18:00">18:00</option>
                    <option value="19:00">19:00</option>
                    <option value="20:00">20:00</option>
                    <option value="21:00">21:00</option>
                    <option value="22:00">22:00</option>
                    <option value="23:00">23:00</option>
                </select>

            </section>
        </section>

        <ins></ins>            
    
        <img id="LoadingForm" src="@PathHelper.UrlStatic/images/global/loading.gif" style="display: none;" />
    
        <input type="submit" value="KAYDET" id="btnAramaKaydet" class="fRight" style="margin-right:30px;" />         
}

<a href="/TiklaAra/UserBlocks" class="ajax blockListLink fIta" data-ga="TiklaAraEngellediklerim">Engellediklerim</a>

<script>
    $(function () {
        PageRender();
        $("select").kendoDropDownList({ autoBind: false });
    });    
</script>
<ins></ins>

trk-fb-world.Debug/Views/TiklaAra/RemainingBalance.cshtml
<section class="information fIta fLeft top35">
    <img src="@PathHelper.UrlStatic/images/icons/information.png" /> <p>Günde ilk 10 dakika ücretsiz sonraki her arama 40 kuruş.</p>
</section>

trk-fb-world.Debug/Views/TiklaAra/UserBlockList.cshtml
@model TurkcellFacebookDunyasi.App.Models.ClickToCallUserBlockListModel

@if (Model.BlockList.Count > 0)
{

    foreach (var item in Model.BlockList)
    {                                                            
                            
        <aside class="friendUser">
            <figure class="fLeft user userMedium">
                <img src="@item.PictureLink" border="0" />
            </figure>
            <label>
                <p>@item.FirstNameView @item.LastNameView</p>
                <a href="javascript:removeBlock('@item.FbId');" class="fIta refresh">engeli kaldır</a>
            </label>
        </aside>

        <ins class="line"></ins>
                                
    }
} else
{
    <section class="fIta">Engellediğiniz arkadaşınız bulunmamaktadır.</section>
}