trk-fb-world.Admin/Controllers/AdminUserController.cs
using TurkcellFacebookDunyasi.Core;
using TurkcellFacebookDunyasi.Core.Interfaces;
using TurkcellFacebookDunyasi.Core.Services;
using Kendo.Mvc.Extensions;
using Kendo.Mvc.UI;
using System;
using System.Web.Mvc;
using System.Collections;
using System.Collections.Generic;

namespace TurkcellFacebookDunyasi.Admin.Controllers
{
    public class AdminUserController : BaseAuthorizedController
    {
        private readonly IAdminRepository repository;
        private readonly AdminService service;
        private readonly AdminAuthService adminAuthService;

        public AdminUserController(IAdminRepository repository, AdminService service, AdminAuthService adminAuthService)
        {
            this.repository = repository;
            this.service = service;
            this.adminAuthService = adminAuthService;
        }

        public ActionResult Default()
        {
            return View();
        }

        public ActionResult k_jRead([DataSourceRequest] DataSourceRequest request)
        {
            return Json(repository.GetAll().ToDataSourceResult(request));
        }

        public ActionResult k_jDelete([DataSourceRequest] DataSourceRequest request, TurkcellFacebookDunyasi.Core.Admin item)
        {
            if (item != null)
                repository.DeleteAndCommit(item);

            return k_jRead(request);
        }


        public ActionResult UserSelfForm()
        {
            return View(repository.GetById(session.AdminId));
        }

        [HttpPost]
        public ActionResult UserSelfForm(TurkcellFacebookDunyasi.Core.Admin entity)
        {
            try
            {
                entity.Id = session.AdminId;
                repository.SaveAndCommit(entity);

                session.FirstName = entity.FirstName;
                session.LastName = entity.LastName;
                session.UserPhoto = entity.FileName;

                return PartialResultSuccess();
            }
            catch (Exception)
            {
                return PartialResultError();
            }
        }

        public ActionResult Form(int? Id)
        {
            if (Id != null)
            {
                ViewBag.AdminAuths = adminAuthService.GetByAdminId(Id.Value);
                return View(repository.GetById(Id.Value));
            }

            return View();
        }

        [HttpPost]
        public ActionResult Form(Core.Admin entity)
        {
            try
            {
                List<string> RequestValues = null;

                if (Request.Form["chAuth"] != null)
                    RequestValues = new List<string>(Request.Form["chAuth"].ToString().Split(new char[] { ',' }, StringSplitOptions.RemoveEmptyEntries));
                
                service.SaveWithPermission(entity, adminAuthService, RequestValues);
                
                return PartialResultSuccess();
            }
            catch (Exception)
            {
                return PartialResultError();
            }
        }
    }
}

trk-fb-world.Admin/Controllers/DefaultController.cs
using TurkcellFacebookDunyasi.Admin.App_Manager;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace TurkcellFacebookDunyasi.Admin.Controllers
{
    public class DefaultController : BaseAuthorizedController
    {

        public ActionResult Default()
        {
            ViewBag.UserName = session.Username;
            return View();
        }

    }
}

trk-fb-world.Admin/Controllers/ModulController.cs
using TurkcellFacebookDunyasi.Admin.Controllers;
using TurkcellFacebookDunyasi.Admin.Models;
using TurkcellFacebookDunyasi.Com.Enums;
using TurkcellFacebookDunyasi.Com.General;
using TurkcellFacebookDunyasi.Core;
using TurkcellFacebookDunyasi.Core.CustomModels;
using TurkcellFacebookDunyasi.Core.Interfaces;
using TurkcellFacebookDunyasi.Core.Services;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace TurkcellFacebookDunyasi.Modul.Controllers
{
    public class ModulController : BaseController
    {
        private readonly ModulService service;

        public ModulController(ModulService service)
        {
            this.service = service;
        }

        public ActionResult Default(IEnumerable<AdminAuth> AdminAuths = null)
        {
            if (AdminAuths != null)
                ViewBag.AdminAuths = AdminAuths;

            return PartialView(service.GetListForAdmin());
        }


        public ActionResult PanelMenu()
        {
            return PartialView(session.Permissions);
        }

        public ActionResult PanelMenuGroup(string groupDesc, Parameter.AdminModulGroup AdminModulGroupEn, Parameter.AdminModulGroup AdminModulGroupTr)
        {
            PanelMenuGroupModel model = new PanelMenuGroupModel();
            model.GroupDescription = groupDesc;
            model.List = session.Permissions.Where(a => (a.ParentId == (int)AdminModulGroupEn || a.ParentId == (int)AdminModulGroupTr) && a.LanguageCode == GlobalVars.LanguageCode).ToList();
            return PartialView(model);
        }
    }
}

trk-fb-world.Admin/Views/AdminUser/Default.cshtml
@model IEnumerable<TurkcellFacebookDunyasi.Core.Admin>

@Helper.BodyNav(Html, "AdminUserList")

<header class="gridToolBar">

    @Html.Partial("HelperControls/GridRefresh")
    @Html.Partial("HelperControls/GridSearch")

</header>

@(Html.Kendo().Grid(Model)
    .Name(KendoManager.GridName)
        
    .Columns(clm =>
    {
        clm.Bound(c => c.FileName).ClientTemplate(KendoManager.ClientTemplateAdminImage("FileName")).Title(Helper.Rsrc("Global", "Image").ToString()).Sortable(false).Filterable(false).Width(60);
        clm.Bound(c => c.FullName);
        clm.Bound(c => c.Username);
        clm.Bound(c => c.LastLoginDate).ClientTemplate(KendoManager.ClientTemplateDate("LastLoginDate"));
        clm.Bound(c => c.IsActive).ClientTemplate(KendoManager.ClientTemplateCheck("IsActive")).Width(30);
        
        clm.Command(cmd =>
        {
            cmd.Custom("Edit").Text(KendoManager.HtmlEditIcon + HttpContext.GetGlobalResourceObject("Global", "Edit").ToString()).Click("kGridGoDetail");
            cmd.Destroy().Text(HttpContext.GetGlobalResourceObject("Global", "Delete").ToString()); } );
    })

    .DataSource(dataSource =>
        dataSource
            .Ajax()
            .ServerOperation(false)
            .Model(model => model.Id(m => m.Id))
            .Read(r => r.Action("k_jRead", "AdminUser"))
            .Destroy(d => d.Action("k_jDelete", "AdminUser"))
            .Events(e => e.Error("kGridOnError"))
        )
            
    .Sortable()
    .Pageable(KendoManager.pagerSettings)
    .Events(e => e.DataBound("kGridOnDataBound"))
    .Reorderable(reorder => reorder.Columns(true))
    .Resizable(resize => resize.Columns(true))
    .Filterable(KendoManager.filterSettings)
)

trk-fb-world.Admin/Views/AdminUser/Form.cshtml
@model TurkcellFacebookDunyasi.Core.Admin

@Helper.BodyNav(Html, "AdminUserList")

@section scripts {

    <script>
        $(function () {
            $('#FullAuth').click(FullAuthCtrl);

            FullAuthCtrl();
        });

        function FullAuthCtrl() {
            ($('#FullAuth').is(":checked")) ? $('.modulList').fadeOut('fast') : $('.modulList').fadeIn('fast');
        }

    </script>
    
}
                
@using (Ajax.BeginForm(null, null, new AjaxOptions { UpdateTargetId = "PageForm", LoadingElementId = "LoadingForm", OnSuccess = "FormOnSuccess" }, new { @id = "PageForm" }))
{    
    <aside class="panel main">
                
        @Html.ValidationMessageFor(m => m.Username)        @Html.LabelFor(m => m.Username)    @Html.TextBoxFor(m => m.Username)
        @Html.ValidationMessageFor(m => m.Password)        @Html.LabelFor(m => m.Password)    @Html.EditorFor(m => m.Password)
        @Html.ValidationMessageFor(m => m.FirstName)       @Html.LabelFor(m => m.FirstName)   @Html.EditorFor(m => m.FirstName)
        @Html.ValidationMessageFor(m => m.LastName)        @Html.LabelFor(m => m.LastName)    @Html.EditorFor(m => m.LastName)
            
        @Html.LabelFor(m => m.Description)    @Html.EditorFor(m => m.Description)
        
        @if (Model != null)
        {    
            @Html.ValidationMessageFor(m => m.LastLoginDate)        @Html.LabelFor(m => m.LastLoginDate)    @Html.TextBoxFor(m => m.LastLoginDate, new { @readonly = "readonly" })        
        }                

        <br />

        @Html.EditorFor(m => m.FullAuth) @Html.LabelFor(m => m.FullAuth)

        <br /><br /> <ins></ins> <br />
        
        @if (ViewBag.AdminAuths == null) { Html.RenderAction("Default", "Modul"); }
        else { Html.RenderAction("Default", "Modul", new { AdminAuths = (IEnumerable<TurkcellFacebookDunyasi.Core.AdminAuth>)ViewBag.AdminAuths }); }

        @Html.Partial("Common/FormFooter")
            
    </aside>
    
    
    <aside class="panel side">
        <aside>

            @{Html.RenderPartial("Common/Upload", new TurkcellFacebookDunyasi.Admin.Models.UploadModel {
                  UploadElementName = "FileName",
                  FileName = (Model != null) ? Model.FileName : "",
                  ImageType = TurkcellFacebookDunyasi.Com.Helpers.UrlHelper.Images.Type.adminusers,
                  ResizeDefault = true,
                  ResizeDefaultW = Parameter.ImageSizes.AdminUser_Default_W,
                  NotRequired = true,
                  NotLiveImg=true
              });}

        </aside>
    </aside>
    
    <aside class="panel side">

        <section class="displayNone">
    
            @if (Model != null) {
                @Html.TextBoxFor(model => model.CreateDate)
            }

        </section>

        @if (Model != null) {
            <aside>
                <h3> @Html.LabelFor(model => model.CreateDate)  </h3> <p>  @Html.DisplayFor(model => model.CreateDate) </p>
                <h3> @Html.LabelFor(model => model.ModifyDate)  </h3> <p>  @Html.DisplayFor(model => model.ModifyDate) </p>
            </aside>
        }

        <aside>
            <p class="checkbox"> @Html.EditorFor(model => model.IsActive) @Html.LabelFor(model => model.IsActive) </p>
        </aside>

    </aside>
}

trk-fb-world.Admin/Views/AdminUser/UserSelfForm.cshtml
@model TurkcellFacebookDunyasi.Core.Admin

@Helper.BodyNav(Html, "AdminUserList", false, false, false)
                
@using (Ajax.BeginForm(null, null, new AjaxOptions { UpdateTargetId = "PageForm", LoadingElementId = "LoadingForm", OnSuccess = "FormOnSuccess" }, new { @id = "PageForm" }))
{    
    <aside class="panel main">
                
        @Html.ValidationMessageFor(m => m.Username)        @Html.LabelFor(m => m.Username)    @Html.TextBoxFor(m => m.Username, new { @readonly = "readonly" })
        @Html.ValidationMessageFor(m => m.Password)        @Html.LabelFor(m => m.Password)    @Html.EditorFor(m => m.Password)
        @Html.ValidationMessageFor(m => m.FirstName)        @Html.LabelFor(m => m.FirstName)    @Html.EditorFor(m => m.FirstName)
        @Html.ValidationMessageFor(m => m.LastName)        @Html.LabelFor(m => m.LastName)    @Html.EditorFor(m => m.LastName)
            
        @Html.LabelFor(m => m.Description)    @Html.EditorFor(m => m.Description)
            
        @Html.ValidationMessageFor(m => m.LastLoginDate)        @Html.LabelFor(m => m.LastLoginDate)    @Html.TextBoxFor(m => m.LastLoginDate, new { @readonly = "readonly" })                        

        @Html.Partial("Common/FormFooter")
            
    </aside>
    
    
    <aside class="panel side">
        <aside>

            @{Html.RenderPartial("Common/Upload", new TurkcellFacebookDunyasi.Admin.Models.UploadModel {
                  UploadElementName = "FileName",
                  FileName = (Model != null) ? Model.FileName : "",
                  ImageType = TurkcellFacebookDunyasi.Com.Helpers.UrlHelper.Images.Type.adminusers,
                  ResizeDefault = true,
                  ResizeDefaultW = Parameter.ImageSizes.AdminUser_Default_W,
                  NotRequired = true
              });}

        </aside>
    </aside>
    
    <aside class="panel side">

        <section class="displayNone">
    
            @Html.EditorFor(m => m.FullAuth)

            @if (Model != null) {
                @Html.TextBoxFor(model => model.CreateDate)
            }

        </section>

        @if (Model != null) {
            <aside>
                <h3> @Html.LabelFor(model => model.CreateDate)  </h3> <p>  @Html.DisplayFor(model => model.CreateDate) </p>
                <h3> @Html.LabelFor(model => model.ModifyDate)  </h3> <p>  @Html.DisplayFor(model => model.ModifyDate) </p>
            </aside>
        }

        <aside>
            <p class="checkbox"> @Html.EditorFor(model => model.IsActive) @Html.LabelFor(model => model.IsActive) </p>
        </aside>

    </aside>
}